/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as CorpoRouteImport } from './routes/corpo'
import { Route as DietaRouteImport } from './routes/dieta'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as PerguntarRouteImport } from './routes/perguntar'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as ProtocoloRouteImport } from './routes/protocolo'
import { Route as RegistroRouteImport } from './routes/registro'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as TermosRouteImport } from './routes/termos'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CorpoRoute = CorpoRouteImport.update({
  id: '/corpo',
  path: '/corpo',
  getParentRoute: () => rootRouteImport,
} as any)
const DietaRoute = DietaRouteImport.update({
  id: '/dieta',
  path: '/dieta',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const PerguntarRoute = PerguntarRouteImport.update({
  id: '/perguntar',
  path: '/perguntar',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocoloRoute = ProtocoloRouteImport.update({
  id: '/protocolo',
  path: '/protocolo',
  getParentRoute: () => rootRouteImport,
} as any)
const RegistroRoute = RegistroRouteImport.update({
  id: '/registro',
  path: '/registro',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosRoute = TermosRouteImport.update({
  id: '/termos',
  path: '/termos',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/corpo': typeof CorpoRoute
  '/dieta': typeof DietaRoute
  '/perfil': typeof PerfilRoute
  '/perguntar': typeof PerguntarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/protocolo': typeof ProtocoloRoute
  '/registro': typeof RegistroRoute
  '/scanner': typeof ScannerRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/corpo': typeof CorpoRoute
  '/dieta': typeof DietaRoute
  '/perfil': typeof PerfilRoute
  '/perguntar': typeof PerguntarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/protocolo': typeof ProtocoloRoute
  '/registro': typeof RegistroRoute
  '/scanner': typeof ScannerRoute
  '/termos': typeof TermosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/comunidade': typeof ComunidadeRoute
  '/corpo': typeof CorpoRoute
  '/dieta': typeof DietaRoute
  '/perfil': typeof PerfilRoute
  '/perguntar': typeof PerguntarRoute
  '/privacidade': typeof PrivacidadeRoute
  '/protocolo': typeof ProtocoloRoute
  '/registro': typeof RegistroRoute
  '/scanner': typeof ScannerRoute
  '/termos': typeof TermosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/corpo'
    | '/dieta'
    | '/perfil'
    | '/perguntar'
    | '/privacidade'
    | '/protocolo'
    | '/registro'
    | '/scanner'
    | '/termos'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/comunidade'
    | '/corpo'
    | '/dieta'
    | '/perfil'
    | '/perguntar'
    | '/privacidade'
    | '/protocolo'
    | '/registro'
    | '/scanner'
    | '/termos'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/comunidade'
    | '/corpo'
    | '/dieta'
    | '/perfil'
    | '/perguntar'
    | '/privacidade'
    | '/protocolo'
    | '/registro'
    | '/scanner'
    | '/termos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  ComunidadeRoute: typeof ComunidadeRoute
  CorpoRoute: typeof CorpoRoute
  DietaRoute: typeof DietaRoute
  PerfilRoute: typeof PerfilRoute
  PerguntarRoute: typeof PerguntarRoute
  PrivacidadeRoute: typeof PrivacidadeRoute
  ProtocoloRoute: typeof ProtocoloRoute
  RegistroRoute: typeof RegistroRoute
  ScannerRoute: typeof ScannerRoute
  TermosRoute: typeof TermosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corpo': {
      id: '/corpo'
      path: '/corpo'
      fullPath: '/corpo'
      preLoaderRoute: typeof CorpoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dieta': {
      id: '/dieta'
      path: '/dieta'
      fullPath: '/dieta'
      preLoaderRoute: typeof DietaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perguntar': {
      id: '/perguntar'
      path: '/perguntar'
      fullPath: '/perguntar'
      preLoaderRoute: typeof PerguntarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocolo': {
      id: '/protocolo'
      path: '/protocolo'
      fullPath: '/protocolo'
      preLoaderRoute: typeof ProtocoloRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/registro': {
      id: '/registro'
      path: '/registro'
      fullPath: '/registro'
      preLoaderRoute: typeof RegistroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos': {
      id: '/termos'
      path: '/termos'
      fullPath: '/termos'
      preLoaderRoute: typeof TermosRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  ComunidadeRoute: ComunidadeRoute,
  CorpoRoute: CorpoRoute,
  DietaRoute: DietaRoute,
  PerfilRoute: PerfilRoute,
  PerguntarRoute: PerguntarRoute,
  PrivacidadeRoute: PrivacidadeRoute,
  ProtocoloRoute: ProtocoloRoute,
  RegistroRoute: RegistroRoute,
  ScannerRoute: ScannerRoute,
  TermosRoute: TermosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
